### ISSUE TITLE
GHC 8.0.1 panics with `Template variable unbound in rewrite rule`

### ISSUE THREAD

**Issue by ocramz** [ekmett/hybrid-vectors#8] opened 2017-06-25 12:25 UTC
The following module makes GHC 8.0.1 panic when`fromList` is uncommented:

```
import qualified Data.Vector.Hybrid as VH
import qualified Data.Vector.Unboxed as VU
import qualified Data.Vector as V

data SHVector a = SHV {-# UNPACK #-} !Int !(VH.Vector VU.Vector V.Vector (Int, a)) deriving (Eq)

fromList :: Int -> [(Int, a)] -> SHVector a
fromList n ll = SHV n (VH.fromList ll)
```

Ticket:
https://ghc.haskell.org/trac/ghc/ticket/13874

**Comment by RyanGlScott** [comment] 2017-06-25 15:56
Yep, this is a duplicate of #7 (and https://ghc.haskell.org/trac/ghc/ticket/13410).

**Closed as completed by RyanGlScott** 2017-06-25 15:56 UTC

**Comment by ocramz** [comment] 2017-06-25 16:51
Thanks @RyanGlScott , I'll be waiting for 8.2.1 then. BTW do you know when it might be released?

**Comment by RyanGlScott** [comment] 2017-06-25 16:58
Like the mythical pegasus, no one knows for sure quite when a new GHC will choose to take flight. Some claim believe they emerge once every year, but they are notoriously skittish, and the most superstitious of GHC watchers might even claim that seeking it too earnestly will only make it harder to find.

...But in all seriousness, the [most recent forecast](https://mail.haskell.org/pipermail/ghc-devs/2017-June/014315.html) predicts early July. That assumes we all of the [release-blocking bugs](https://ghc.haskell.org/trac/ghc/query?status=!closed&priority=high&priority=highest&milestone=8.2.1&order=priority) have been fixed by then, of course ;)
